[build]
  command = "npm run build"  # Comando de compilación personalizado
  functions = "functions"  # Directorio donde se encuentran las funciones de servidor

[functions]
    [functions.path]
    external_node_modules = [
      "module-one",
      "module-two"
    ]